### ISSUE TITLE
Error: cannot open file: jsony

### ISSUE THREAD

**Issue by AhmedWagdi1** [trev-dev/timew-billable#10]
After running the command `nim c -d:release src/billable.nim` it returns this error `Error: cannot open file: jsony`

**Comment by trev-dev** [comment]
Have you got your dependencies installed? `jsony` is a dependency that should be gathered via nimble first.

**Comment by AhmedWagdi1** [comment]
I have got the dependencies following the structure in the readme file :

1. Install the nimble dependencies with nimble install -l
2. Build a release version with nim c -d:release src/billable.nim  >> and the error pops here.

also when I tried to download the binary from your releases and add it to the extensions folder inside Time Warrior using `timew billable` it returned this error :

```
returned 255 without producing output.

```
please note that I have already added the required config to time/task Warrior guided by your `example config` file

**Comment by trev-dev** [comment]
I am not able to replicate this problem, using NixOS.  Nim version 2.0, nimble 0.14.2. 

config:
```cfg
billable = 80
billable.voltage = 65
billable.task_marker = :
billable.csv_name = /tmp/billables.csv
```

Please provide more detail so I can help narrow it down.

**Comment by AhmedWagdi1** [comment]
here is the output of my terminal during the process :

```
ahmed@ahmed-H81M-E:~/Downloads/timew-billable$ nimble install -l
   Warning: Using project local deps mode
  Verifying dependencies for billable@0.2.4
     Info:  Dependency on csvtools@>= 0.2.1 & < 1.0 already satisfied
  Verifying dependencies for csvtools@0.2.1
     Info:  Dependency on jsony@>= 1.1.3 & < 2.0 already satisfied
  Verifying dependencies for jsony@1.1.5
     Info:  Dependency on nancy@>= 0.1.1 & < 1.0 already satisfied
  Verifying dependencies for nancy@0.1.1
     Info:  Dependency on ansiparse@>= 0.2.0 already satisfied
  Verifying dependencies for ansiparse@0.4.0
     Info:  Dependency on termstyle@>= 0.1.0 & < 1.0 already satisfied
  Verifying dependencies for termstyle@0.1.0
 Installing billable@0.2.4
   Building billable/billable using c backend
  Success:  billable installed successfully.
ahmed@ahmed-H81M-E:~/Downloads/timew-billable$ nim c -d:release src/billable.nim
Hint: used config file '/home/ahmed/.choosenim/toolchains/nim-2.0.0/config/nim.cfg' [Conf]
Hint: used config file '/home/ahmed/.choosenim/toolchains/nim-2.0.0/config/config.nims' [Conf]
Hint: used config file '/home/ahmed/Downloads/timew-billable/config.nims' [Conf]
............................................................................................................................
/home/ahmed/Downloads/timew-billable/src/billable.nim(2, 8) Error: cannot open file: jsony
ahmed@ahmed-H81M-E:~/Downloads/timew-billable$ 
```

**Comment by AhmedWagdi1** [comment]
@trev-dev please note that the error `Error: cannot open file: jsony` is not stopping the build process and it is already built and working as expected,, it was my bad I didn't notice that and only focused on the error. 
apologizes . closing the issue
