### ISSUE TITLE
How can I configure simultaneous generation of CSV and terminal reports?

### ISSUE THREAD

**Issue by AhmedWagdi1** [trev-dev/timew-billable#11]
While I understand this may not be considered an issue, and I acknowledge there might not be a dedicated space for such inquiries, I occasionally find myself in a situation where I need to review the billable report concurrently with my ongoing tasks. Specifically, I would like to inquire if there is a method to generate a CSV report simultaneously with viewing the report in the terminal. Is there a recommended approach for achieving this dual functionality?

My current configuration is as follows:

```
billable = 150
billable.voltage = 100
billable.task_marker = :
billable.render = csv
billable.render = terminal
billable.csv_name = /home/ahmed/Desktop/billables.csv
```

However, it seems that this configuration only generates a terminal report and does not update the CSV report.

**Comment by trev-dev** [comment]
Hello from the future.  I have no idea why it took me this long to get to this.
https://github.com/trev-dev/timew-billable/commit/420e0e7afec23c3790d70f470821f78a2efec107

Set `billable.render = both` to get both outputs at once.
